### ISSUE TITLE
Tracking: Elixir Bindings

### ISSUE THREAD

**Issue by asg017** [asg017/sqlite-vss#51]
Do you have any issues using the new Elixir bindings for sqlite-vss? Comment on this issue with any bugs or crashes you come across, or with suggestions on how to make it better.

TODOs for Elixir bindings:

- [ ] elxir docs work
- [ ] site documentation
- [ ] dedicated ecto example under `examples/`?
- [ ]  Add elixir test to test.yaml workflow?
