### ISSUE TITLE
Tracking: Ruby Bindings

### ISSUE THREAD

**Issue by asg017** [asg017/sqlite-vss#52]
Do you have any issues using the new Ruby bindings for `sqlite-vss`? Comment on this issue with any bugs or crashes you come across, or with suggestions on how to make it better.

TODOs for Ruby bindings:
- [ ] rubygems.org README
- [ ] site documentation
- [ ] Some ruby example
- [ ] Add ruby test to `test.yaml` workflow?
